name: Build StreamFX

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CACHE_VERSION: "2022-12-02"

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        runner: [ "windows-2022" ]
        name: [ "Windows" ]
        compiler: [ "MSVC"]
        qt: [ 6 ]
        include:
          - compiler: "MSVC"
            package_name: "windows"
            CMAKE_SYSTEM_VERSION: "10.0.20348.0"
            CMAKE_GENERATOR: "Visual Studio 17 2022"
            CMAKE_GENERATOR_PLATFORM: "x64"
    runs-on: "${{ matrix.runner }}"
    name: "${{ matrix.name }} (${{ matrix.compiler }})"
    env:
      CMAKE_GENERATOR: "${{ matrix.CMAKE_GENERATOR }}"
      CMAKE_GENERATOR_PLATFORM: "${{ matrix.CMAKE_GENERATOR_PLATFORM }}"
      CMAKE_SYSTEM_VERSION: "${{ matrix.CMAKE_SYSTEM_VERSION }}"

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: "Gather Information"
      id: info
      shell: bash
      run: |
        # Define buildspec file
        buildspec="${{ github.workspace }}/third-party/obs-studio/buildspec.json"

        # Prebuilt Dependencies Version
        IFS=$'\n' buildspecdata=($(node tools/buildspec.js "${buildspec}" "prebuilt" "windows-x64"))
        echo "obs_deps_version=${buildspecdata[0]}" >> "$GITHUB_ENV"
        echo "obs_deps_hash=${buildspecdata[1]}" >> "$GITHUB_ENV"
        echo "obs_deps_url=${buildspecdata[2]}" >> "$GITHUB_ENV"

        # Qt Version
        IFS=$'\n' buildspecdata=($(node tools/buildspec.js "${buildspec}" "qt${{ matrix.qt }}" "windows-x64"))
        echo "qt_version=${buildspecdata[0]}" >> "$GITHUB_ENV"
        echo "qt_hash=${buildspecdata[1]}" >> "$GITHUB_ENV"
        echo "qt_url=${buildspecdata[2]}" >> "$GITHUB_ENV"

        # libOBS Version
        echo "obs_version=$(cd "${{ github.workspace }}/third-party/obs-studio" && git describe --tags --long)" >> "$GITHUB_ENV"

    - name: "Install Dependencies"
      run: |
        choco install cmake ninja 7zip --no-progress

    - name: "Build zlib"
      run: |
        # Tải zlib
        curl -LO https://zlib.net/zlib131.zip
        # Giải nén zlib
        7z x zlib131.zip -o"zlib-1.3.1"
        ls zlib-1.3.1
        # Tạo thư mục build
        cmake -S zlib-1.3.1/zlib-1.3.1 -B build/zlib -G "Ninja" `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/zlib-install
    
        cmake --build build/zlib --target install


    - name: "Dependency: Prebuilt OBS Studio Dependencies (Cache)"
      id: obsdeps-cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/build/obsdeps"
        key: "obsdeps-${{ env.CACHE_VERSION }}"

    - name: "Dependency: Prebuilt OBS Studio Dependencies"
      id: obsdeps
      if: ${{ steps.obsdeps-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        curl --retry 5 --retry-delay 30 -jLo /tmp/obsdeps.zip "${{ env.obs_deps_url }}"
        if [[ ! -f "${{ github.workspace }}/build/obsdeps" ]]; then mkdir -p "${{ github.workspace }}/build/obsdeps"; fi
        7z x -y -o"${{ github.workspace }}/build/obsdeps" -- "/tmp/obsdeps.zip"

    - name: "Configure"
      continue-on-error: true
      shell: bash
      run: |
        cmake \
          -S "${{ github.workspace }}" \
          -B "${{ github.workspace }}/build/ci" \
          -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" \
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
          -Dlibobs_DIR="${{ github.workspace }}/build/obs/install" \
          -DQt${{ matrix.qt }}_DIR="${{ github.workspace }}/build/qt" \
          -DFFmpeg_DIR="${{ github.workspace }}/build/obsdeps" \
          -DCURL_DIR="${{ github.workspace }}/build/obsdeps"

    - name: "Build OBS Studio"
      run: |
        cmake --build build/obs --config RelWithDebInfo --target obs-frontend-api

    - name: "Install OBS Studio"
      run: |
        cmake --install build/obs --config RelWithDebInfo --component obs_libraries

    - name: "Upload Build Artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: "${{ matrix.runner }}-${{ matrix.compiler }}"
        path: build/package
