name: Build StreamFX

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Visual Studio
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # Install dependencies
    - name: Install Dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress
        choco install ninja --no-progress

    # Configure project
    - name: Configure with CMake
      run: |
        cmake -S . -B build -G "Ninja" ^
          -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
          -DCMAKE_C_COMPILER="cl.exe" ^
          -DCMAKE_CXX_COMPILER="cl.exe" ^
          -DZLIB_LIBRARY="D:/libs/zlib.lib" ^
          -DZLIB_INCLUDE_DIR="D:/libs/zlib/include" ^
          -DENABLE_OBS_SCRIPTS=OFF

    # Build project
    - name: Build with CMake
      run: cmake --build build --config RelWithDebInfo

    # Optional: Run tests
    - name: Run Tests
      run: |
        ctest --test-dir build --output-on-failure
